const testValidateTitle = require('./test-validate-title')
const testValidateDescription = require('./test-validate-description')
const testValidateUrl = require('./test-validate-url')
const testValidateLinks = require('./test-validate-links')
const testValidateP2Pcommons = require('./test-validate-p2pcommons')
const testValidateType = require('./test-validate-type')
const testValidateSubtype = require('./test-validate-subtype')
const testValidateMain = require('./test-validate-main')
const testValidateAvatar = require('./test-validate-avatar')
const testValidateAuthors = require('./test-validate-authors')
const testValidateFollows = require('./test-validate-follows')
const testValidateContents = require('./test-validate-contents')
const testValidatePartial = require('./test-validate-partial')
const testValidateOnFollow = require('./test-validate-on-follow')
const testValidateOnRegister = require('./test-validate-on-register')
const testValidateParents = require('./test-validate-parents')
const testValidate = require('./test-validate')

testValidateTitle()
testValidateDescription()
testValidateUrl()
testValidateLinks()
testValidateP2Pcommons()
testValidateType()
testValidateSubtype()
testValidateMain()
testValidateAvatar()
testValidateAuthors()
testValidateParents()
testValidateFollows()
testValidateContents()
testValidatePartial()
testValidateOnFollow()
testValidateOnRegister()
testValidate()
